name: AEM Dev CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'develop-test'
      artifact_version:
        description: "Enter the artifact version to build"
        required: true
        default: "2.0.0"  # Default version if not specified
env:
  AEM_PACKAGE: "saudi-tourism.all-${{ github.event.inputs.artifact_version }}.zip"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests -Dcheckstyle.skip -DvsVersion=${{github.event.inputs.artifact_version }} 

      - name: Display structure of all jar/files
        run: find . -type f -name "*.zip"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sta-build-artifacts
          path: ./all/target/*.zip
          compression-level: 0
            
  deploy_prodset1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Package
        uses: actions/download-artifact@v4
        with:
          name: sta-build-artifacts

      - name: Display downloaded files
        run: ls -R

      - name: Deploying on Prod Author
        env:
          AEM_USERNAME: ${{ secrets.AEM_USERNAME }}
          AEM_PASSWORD: ${{ secrets.AEM_PASSWORD }}
          AEM_HOST: 'https://3bf0-93-112-36-211.ngrok-free.app'
        run: |
          curl -u "$AEM_USERNAME:$AEM_PASSWORD" \
           -F file=@"$AEM_PACKAGE" \
           -F name="saudi-tourism.all" \
           -F force=true \
           -F install=true \
           "$AEM_HOST/crx/packmgr/service.jsp"

      - name: Wait for AEM to be fully Up
        run: |
          MAX_RETRIES=30
          RETRY_INTERVAL=10
          for ((i=1; i<=$MAX_RETRIES; i++)); do
            INACTIVE_BUNDLES=$(curl -u "$AEM_USERNAME:$AEM_PASSWORD" -s "$AEM_HOST/system/console/bundles.json" | jq '.data[] | select(.state != "Active" and .state != "Fragment")')
            if [ -z "$INACTIVE_BUNDLES" ]; then
              echo "All AEM bundles are active."
              exit 0
            else
              echo "Some AEM bundles are still not active. Waiting..."
              sleep $RETRY_INTERVAL
            fi
          done
          echo "AEM bundles did not become active within the expected time."
          exit 1
          
  deploy_prodset2:
    needs: deploy_prodset1
    runs-on: ubuntu-latest
    environment: prodset1
    steps:
      - name: Download Build Package
        uses: actions/download-artifact@v4
        with:
          name: sta-build-artifacts

      - name: Display downloaded files
        run: ls -R

      - name: Upload and Install package to AEM
        env:
          AEM_USERNAME: ${{ secrets.AEM_USERNAME }}
          AEM_PASSWORD: ${{ secrets.AEM_PASSWORD }}
          AEM_HOST: 'https://3bf0-93-112-36-211.ngrok-free.app'
        run: |
          curl -u "$AEM_USERNAME:$AEM_PASSWORD" \
           -F file=@"$AEM_PACKAGE" \
           -F name="saudi-tourism.all" \
           -F force=true \
           -F install=true \
           "$AEM_HOST/crx/packmgr/service.jsp"
      

