
name: Test Connection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Temporary Branch Selection'
        required: true
        default: 'develop-test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.DISP_AZURE_CRED }}
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage -h 
    - name: Install SSH Extension for Azure CLI
      run: |
          az extension add --name ssh
          az ssh config --ip * --file ./ssh_config --keys-destination-folder ./azure-keys
          cat ssh_config
    - name: Set up SSH private key
      run: |
          mkdir -p .ssh
          echo "${{ secrets.SSH_KEY }}" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

    - name: SSH into Azure Arc-enabled machine and run a command
      run: |
          az ssh arc --resource-group "VisitSaudi_Arc_Servers" --name "Acc-Dispatcher1-R" --local-user purgeuser --private-key-file ".ssh/id_rsa" -- -o StrictHostKeyChecking=no  'sudo echo "test" > /home/purgeuser/test.html'
  
    - name: Copy file to Azure Arc server
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          echo "before scp command"
          az ssh config --ip \* --file ./sshconfig
          scp -F ./sshconfig purgeuser@10.100.5.56:~/home/purgeuser
          
          
