name: Test Connection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Temporary Branch Selection'
        required: true
        default: 'develop-test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.DISP_AZURE_CRED }}
    - name: Set Azure CLI dynamic install
      run: |
          az config set extension.use_dynamic_install=yes_without_prompt
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: 2.45.0
        inlineScript: |
          az account show
          az storage -h
          az resource list --resource-type "Microsoft.Compute/virtualMachines" --output table
          mkdir sta_keys
          echo "${{ secrets.SSH_KEY }}" > sta_keys/id_rsa
          chmod 400 sta_keys/id_rsa
          cat sta_keys/id_rsa
          pwd
          az ssh arc --subscription d39b9572-8709-43ac-bc38-bc3cd691475d --resource-group "VisitSaudi_Arc_Servers" --name "acc-dispatcher2-r" --local-user "purgeuser" --private-key-file sta_keys/id_rsa -- -o StrictHostKeyChecking=no 'echo "Connection Success!"' 'sudo mkdir /tmp/test_upload' 'cat > /tmp/test_upload < sta_keys/id_rsa'
